### ISSUE TITLE
Unable to reinvite to server

### ISSUE THREAD

**Issue by timothymeadows77** [Fabricio20/LewdWiki#11]
I kicked lewdbot and want it back in my server on discord how do i do that it wont show my server at all

**Comment by Fabricio20** [comment]
Make sure you are logged in at https://discordapp.com/

**Comment by Zepherah** [comment]
This. 
I also had a problem with it not responding to commands.  I figured I could help it by kicking it and then trying to re add it, which didn't work, and isn't showing up on my server at all either.
I'm logged in on discord, on the discord website. I don't know where to go from there.
