### ISSUE TITLE
giving cookies

### ISSUE THREAD

**Issue by theredood** [Fabricio20/LewdWiki#122]
how do i give cookies to people with a space in their name?
when i do /cookies <name> <amount> it works, however when i try this for people with a space in their name it refuses to give the cookies.
That's not a cookie count! Choose the amount of cookies you want to send.
things i have tried so far are:
type their name
use the @name
do name_rest_of_name

**Comment by Fabricio20** [comment]
Hello, can yout ry placing their name between "?

Like give "User name" amount

**Comment by theredood** [comment]
That seems to work, thanks
