### ISSUE TITLE
How to get POWER user permissions?

### ISSUE THREAD

**Issue by the-real-masked-developer** [Fabricio20/LewdWiki#124]
when I try to do **l!music volume 2** , I get an error message : "This command is restricted to POWER users only." How to fix it please, I can't see nothing about this on your Wiki :)

**Comment by Fabricio20** [comment]
Power users are donors, if you wish to change the music volume either right click the bot and drag the volume bar or become a patron to get access to global volume.

Global volume is a CPU expensive task which is the reason it's locked behind a paywall.
