### ISSUE TITLE
l!prune command various bugs

### ISSUE THREAD

**Issue by yeeeeeet** [Fabricio20/LewdWiki#131]
The L!prune command parameters do not work as described. As it is phrased in help, L!prune 30 @Someone Deletes last 30 messages from Someone. However, the actual functionality of L!prune is different

If I type l!prune 3 @wumpus for example, It will not delete the last 3 messages from Wumpus, it would delete any messages Wumpus typed within the last 3 messages. and one of those 3 would be my typing the prune command. If Wumpus types 3 messages, then I type 2, and then use a l!prune 3 command, nothing will be pruned, as Wumpus did not type within the last 3 messages. 

Additionally, the L!prune command on does not work properly if Lewd Bot uses it on herself. If You type L!prune 4 @LewdBot, it will delete the last 4 messages, as if the argument for lewd bot was not called.

Additionally, the output will state that 1 message was deleted, regardless of the number of messages deleted.

**Comment by wumpus** [comment]
Hi, my name's Wumpus, and I'm an IRC adddict.

**Comment by Fabricio20** [comment]
Will look into it.

**Comment by Fabricio20** [comment]
I think these issues have been addressed as of now so I'm placing it under testing, will close once I confirm they have been fixed.
