### ISSUE TITLE
l!hentai is sort of useless

### ISSUE THREAD

**Issue by yeeeeeet** [Fabricio20/LewdWiki#132]
l!hentai does absolutely nothing a good portion of the time. I have yet to see it work on my server after extensive testing. L!hentai with no arguments, when it does cause the bot to react, she simply states that "there are no images on Danbooru." The only other arguments that I got LewdBot to acknowledge are Fjorm, Zelda, and Medli, and for all of those, LewdBot claimed that there are no images with this criteria, which I assure you is not the case. This has been tested several times last night, and I have spent half an hour trying it again here before I wrote this report, to no avail. l!r34 and l!iateacrayon are both completely functional, but l!hentai is not working correctly at the moment.

**Comment by Fabricio20** [comment]
NSFW commands have been broken since ever. The API for Danbooru and Rule34 which me and other bots (Like Mantaro) use is unstable and discord doesn't like that.

**Comment by Fabricio20** [comment]
This scenarion seems to have changed since this issue was opened (due to a rewrite of the command and cache).
