### ISSUE TITLE
NSFW commands do not work

### ISSUE THREAD

**Issue by Aenyl** [Fabricio20/LewdWiki#141]
Hello, I can't manage to get the NSFW commands to work. None of them work, and Lewdbot does not even respond to them.
![bug lewdbot](https://user-images.githubusercontent.com/42447996/44225088-b9d46d00-a18c-11e8-8031-a0270bf289a8.PNG)
Maybe I'm doing something wrong ? I tried using arguments, too, but it didn't work. Lewdbot just ignores the messages.
Most of the other commands work fine, though.

**Comment by Fabricio20** [comment]
Did you enable NSFW module?

**Comment by Aenyl** [comment]
Yes, I enabled it. I tried to use these commands both in a regular channel and in a NSFW channel, it worked for neither of the two.

**Comment by Fabricio20** [comment]
I believe these should be working by now.
