### ISSUE TITLE
Cookies.

### ISSUE THREAD

**Issue by SkeJm** [Fabricio20/LewdWiki#149]
Command l!cookies doesn't work (also tried l!cookie)

**Comment by Fabricio20** [comment]
How does it not work?

Just tested and it's working properly. The cookie command is an Embed so make sure you don't have the `Show website preview info from links when pasted into chat` toggled off (It's under Settings -> Text & Image).

**Comment by speedcat9999** [comment]
i have found an issue that causes this command not to work correctly (among other commands) lewdbot seems to not handle spaces in usernames/roles well.

**Comment by Fabricio20** [comment]
I think that is a bad case of documentation, LewdBot ignores spaces by default (she uses it to split args), which can lead up to some detection failures.

In any case, you can use " around the name to force her to split there. `L!cookies "Fabri cio 20"`
