### ISSUE TITLE
Prefix r34 loli

### ISSUE THREAD

**Issue by Myrobinz** [Fabricio20/LewdWiki#2]
When typing Prefix r34 loli it doesnt load/send picture properly and displays blank screen 99.9% of the time.
![2017-01-12 1](https://cloud.githubusercontent.com/assets/25089059/21908109/c457eaa2-d912-11e6-8e22-b3236f581206.png)

**Comment by Fabricio20** [comment]
Hm, managed to reproduce, not sure what is the cause, I'll check later.

**Comment by Fabricio20** [comment]
As of some minutes ago I think I got this fixed, please reopen the issue if the rate of failure is this high again.
