### ISSUE TITLE
Lewdbot Offline not responding

### ISSUE THREAD

**Issue by KJ03** [Fabricio20/LewdWiki#23]
I'm having a problem which I think is happening to everyone but, LewdBot went offline and doesn't respond to any commands now I do think maybe it's having updates or IDK there's a bug or glitch I tried banning and kicking it and re-inviting it and it joined hopefully this is sorted soon 

![image](https://cloud.githubusercontent.com/assets/23220073/25763593/bedaea44-31db-11e7-88bd-29f7e2cca982.png)

**Comment by Fabricio20** [comment]
Closing this as this is probably relevant to a maintenance, please check #news on LewdBot's support guild for Maintenace downtime alerts.
