### ISSUE TITLE
Allow to change the logs channel for the Music Module

### ISSUE THREAD

**Issue by GeorgesHarrison** [Fabricio20/LewdWiki#29]
It could be fine to be able to change the output channel for the music module. 
Currently, the current song is logged into the by default channel.

**Comment by Fabricio20** [comment]
Already a feature, try the `setmusic` command,

**Comment by macks2008** [comment]
tried this myself and it gave me an almost completely un-actionable error ("Error while updating music chat channel, please try again later."). Sure I can try again later like the error says, but can't you at least give me an idea what went wrong?
