### ISSUE TITLE
Commands problem (sort of)

### ISSUE THREAD

**Issue by Canadianpigman** [Fabricio20/LewdWiki#3]
Basicllay i just want a way to ban some commands for everyone like the r34 and hentai commands is there any or any upcoming feature for this? sorry for my horrible english its my second languge

**Comment by minhjemmesiden** [comment]
yo could just disable to module to my understanding but I am new to this.

**Comment by Fabricio20** [comment]
That's correct, the only option for now is to disable the NSFW module `modules disable NSFW`.

A new permission feature is coming out soon that will allow you to limit which roles can use which commands, so that could be helpful.

**Comment by Canadianpigman** [comment]
ok thanks

**Comment by Canadianpigman** [comment]
So using the modules command i have done what i wanted thanks for the help. :)
