### ISSUE TITLE
Music Problem

### ISSUE THREAD

**Issue by Ninjacam100** [Fabricio20/LewdWiki#38]
When i play some music it works fine, but when i use it again or at least a couple times and use it on the music that doesn't work, it says, "PlayList already contains {0}" and wont let me play that music at all.

**Comment by UselessLewdSupport** [comment]
you can visit your current playlist with `@LewdBot Lm list`. The Playlist contains all songs that you added and did not remove again with either `@LewdBot Lm remove numberinlist` or `@LewdBot Lm clear` to delete the whole playlist. New songs will be added the playlist, if you already added a song you can relisten to it by typing `@LewdBot Lm play numberinlist`, f.e. if the song is number 5 in the list the correct command would be `@LewdBot Lm play 5`

**Comment by Ninjacam100** [comment]
Thank you so much!
