### ISSUE TITLE
Music Error while playing

### ISSUE THREAD

**Issue by SeekNDStroys** [Fabricio20/LewdWiki#39]
When i was Playing a life steam For 1 min It told me Error while playing ( song name ) And played a random Song..,and it keep happining,, And when i play another song It stays for 4 min then tells me Disconnected. Reason: Noone is listening..

**Comment by DrReality** [comment]
I have a similar problem. But mine just plays every song fast forwarded. I don't know how to fix it

**Comment by Fabricio20** [comment]
Hm, for now, try `L!music fix`

**Comment by DrReality** [comment]
Thank you! It worked so well! It didn't even delete the queue I spent a while making
