### ISSUE TITLE
Lewdbot don't reponding to commands

### ISSUE THREAD

**Issue by 42OnlyTruth** [Fabricio20/LewdWiki#4]
We disconnected from the server, and when we come back, Lewdbot did'nt longer respond to join/leave and stop and even if he was saying that the music is playing there wasn't any sound. We tryed to kick him to reinvite him to the server but now he don't respond to any command

**Comment by Fabricio20** [comment]
The death issue is known, I have been working for more than a week now on trying to fix it, I believe with the newest update (today) it should be back to normal.
