### ISSUE TITLE
Cannot search R34 on an NSFW channel

### ISSUE THREAD

**Issue by deathpenguin53** [Fabricio20/LewdWiki#47]
![discord issues](https://user-images.githubusercontent.com/30302733/28392712-f5528d9c-6c97-11e7-8cb0-4cf525359ea5.png)
![discordissues2](https://user-images.githubusercontent.com/30302733/28392743-1aee0428-6c98-11e7-80cb-7f99d3c22a94.png)

I've also tried making new text channels, creating new servers, deleting servers, and deleting text channels. Nothing seems to fix this for me.

**Comment by Fabricio20** [comment]
That is an issue with a shadow update on discord, for now rename the channel to `nsfw-` or wait some more hours til' the restart.
