### ISSUE TITLE
R34 Error?

### ISSUE THREAD

**Issue by SuicidalTears** [Fabricio20/LewdWiki#49]
I got the error on the server I host stating
"Michael(Nudist): Error while fetching images from Danbooru! (Nothing found?)"
Any assistance would be appreciated.

**Comment by Fabricio20** [comment]
Looks like Danbooru banned LewdBot's ip addr, nothing I can do to fix it for now.

**Comment by Greenlink74** [comment]
Can you leave a note discussing this issue on the LB website?

**Comment by Fabricio20** [comment]
Closing issue as the new implementation seems to have fixed it.
