### ISSUE TITLE
You do not have permission to use this command! (despite being an admin)

### ISSUE THREAD

**Issue by macks2008** [Fabricio20/LewdWiki#5]
despite having the Administrator role & permission in my server's master role list, I cannot seem to run any commands, including @LewdBot perms. If I have to wake up the server's founder because of this, or if I, worse yet, wake him up and find that he can't even manage permissions, I will be, to say the least, very irritated.

**Comment by macks2008** [comment]
@Fabricio20 I summon thee! Waketh from thy slumber if thou beest resting at this hour!

**Comment by Fabricio20** [comment]
The admin is LewdBot admin, which can be added by using `@LewdBot admin add @user` by the server owner.
