### ISSUE TITLE
Possible work around for R34 being broken.

### ISSUE THREAD

**Issue by AliStarr** [Fabricio20/LewdWiki#52]
A solution may be using [this compiled list](https://www.reddit.com/r/iateacrayon/wiki/list) of links from Imgur. It's updated pretty frequently.

Take the query, search the list, pull the album, get a random image from the returned album. Will probably be somewhat more accurate than the last system where it seemed to pull pretty much anything even if it was only very slightly relevant.

That list has fields for character name and series/game/fetish so you could do some refining on the query for more accurate results. 

Limiting factors on this approach are that the Imgur API has a strict limit on calls a month. If you want to avoid that then I hope you like parsing raw HTML or paying for their API to get more calls.

**Comment by Fabricio20** [comment]
I mean, I like the idea, I'm just not sure how to properly search on it since one could go for either the name or the category (and maybe want to be specific).

**Comment by AliStarr** [comment]
I'm not the most experienced dev but you could possibly add a second optional parameter to the R34 search separated by a comma or a similar character so you could return specific results. Otherwise just iterate though the list and if the person is searching for a Game like Overwatch, If it doesn't find anything in the character name field then it would go though the next field until it finds a match or falls though.

Theres a few thousand entries in that list so the risk of returning a duplicate/wrong result is somewhat an issue but if the wrong result is returned then they have the option of adding the series/game/etc into the separate parameter to refine their search.

I have a file that I extracted from that link and formatted into key, value, value pairs with the Character name as the key, the context as the first value and the Imgur album link as the 2nd value.
[raw.txt](https://github.com/Fabricio20/LewdWiki/files/1219385/raw.txt)

Not sure if any of this helps but I'm happy to provide anything else you might need.

**Comment by Fabricio20** [comment]
Ok, I managed to code a search system which works based on confidence levels, the higher the confidence, the more accurate it may be.

So far my tests have succeeded in filtering things like 'Alice Resident' (for Alice [Resident Evil]) from the list of 'Alice' on that page.

Next step now is to code a cache system so I don't get banned on imgur (reddit page is already cached).

Any suggestions for the command name? I plan on releasing this as a new command since if I touch r34 people complain that their paheal content doesn't show up.

**Comment by Fabricio20** [comment]
As of internal commit #6af38775 on `LewdBot/NSFW` this feature is implemented.

Still taking command name suggestions though.

**Comment by AliStarr** [comment]
Awesome. The folks on my server send you their thanks.

A name for the command could just be "lewd".

How are you planning to do caching? The albums are updated fairly frequently.

**Comment by Fabricio20** [comment]
Currently I cache the album page after requesting it from the api, which means I have a json-array with all image links and I just need to iterate over it and send as embed to discord.

The cache currently expires every restart, which should normalize at around 24h.
