### ISSUE TITLE
LewdBot not working anymore?

### ISSUE THREAD

**Issue by mario610** [Fabricio20/LewdWiki#53]
![help](https://user-images.githubusercontent.com/985266/29341081-e902d4ec-81e7-11e7-99e3-1dd5f868da1d.PNG)
I don't know why its not working I set lewd bots prefix to - so it can't be that

**Comment by Fabricio20** [comment]
This was fixed internally as of now, next restart will make it work again, please wait for it to happen. (Up to 24h).
