### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by Shiidon** [Fabricio20/LewdWiki#54]
lewdbot is offline well commands doesn't works, i tried to kick him and reinvite him but not works, can i have help plz? :p

**Comment by Fabricio20** [comment]
Known, as posted on the support guild:
"Something weird happened and my dedi went down, after a restart Discord is reconnecting me like crazy so I can't keep her up, will fix once I'm home"

**Comment by Shiidon** [comment]
thx men :)
