### ISSUE TITLE
The music is always stoping

### ISSUE THREAD

**Issue by Kendiii** [Fabricio20/LewdWiki#59]
when im hearing music from the lewdbot , the music stops every 2 seconds. and starts after 3 seconds more less. what should i do. this thing is pissing me off, cause i cant hear the music clearly

**Comment by Fabricio20** [comment]
I'm aware of this issue and looking into a new server to handle music.

**Comment by Fabricio20** [comment]
A new server has been deployed (Galax). Shards `40` up to `79` are currently on it testing the stability.

If everything goes according to plan, I will be able to migrate all shards in about two weeks.

**Comment by Fabricio20** [comment]
A new music system was deployed yesterday, currently testing how it behaves.

**Comment by Fabricio20** [comment]
Just reached 456 audio streams without a single issue, looking forward to Saturday (tomorrow) to see how it behaves under (ultimate) heavy load.

**Comment by Fabricio20** [comment]
No problems so far, closing this issue.
