### ISSUE TITLE
Pictures won't appear for me when i type in the command for it 

### ISSUE THREAD

**Issue by JustSomeWeeb** [Fabricio20/LewdWiki#64]
It used to show me r34 and not hentai now it just doesn't show both 
![image](https://user-images.githubusercontent.com/32890406/31700109-b9114c38-b38c-11e7-822d-55e618748b53.png)

![image](https://user-images.githubusercontent.com/32890406/31700120-d767bb68-b38c-11e7-88ce-85a73534a30d.png)

**Comment by Fabricio20** [comment]
Can I get the server part from the `L!shard` command?

**Comment by Fabricio20** [comment]
Should be fixed.
