### ISSUE TITLE
Lewd Bot Cookies

### ISSUE THREAD

**Issue by helpplox** [Fabricio20/LewdWiki#65]
All cookies have disappeared and reset to zero. No idea how or why. Even after receiving cookies, total number is 0. Cannot give cookies to others.

**Comment by Fabricio20** [comment]
Can you get me your account ID real quick? (Google how to get account id Discord)

As a note to everyone: Cookies are safe, I got backups of the old database and the new database is correct, its JUST LewdBot/memory cache not updating correctly.
