### ISSUE TITLE
Music Queue clear Command not working?

### ISSUE THREAD

**Issue by MVLKS** [Fabricio20/LewdWiki#72]
Whenever I do [prefix]lm/im clear, it keeps returning "Unknown subcommand", this also occurs even when you @ the bot.

![temp1](https://user-images.githubusercontent.com/21109730/32193903-27c4218a-bd8f-11e7-95ea-11640e2bf305.png)

I am unsure if this a bug.

**Comment by Fabricio20** [comment]
This has been fixed for at least a month now :)
