### ISSUE TITLE
The Cookie Jar

### ISSUE THREAD

**Issue by Rodney1234567890** [Fabricio20/LewdWiki#73]
The cookie jar is empty! No cookies for you this time. however we spam the cookies into the jar

**Comment by Green-Ivy** [comment]
l!cthrow allows you to put 0 cookies. I know, kind of strange. If you want to actually put cookies in, give a number after the command.

**Comment by Fabricio20** [comment]
That's a bug.

**Comment by Fabricio20** [comment]
Actually not a valid bug, she just replies with "That's not a valid amount of cookies".
