### ISSUE TITLE
bot is not answering

### ISSUE THREAD

**Issue by firehunter02** [Fabricio20/LewdWiki#76]
bot isn't offline and I use the prefix right way.But it's not answering.Can you help me?

**Comment by Fabricio20** [comment]
Create a new text channel and try to use her there. Tell me how it goes.

**Comment by firehunter02** [comment]
ok its work now.Thanks a lot :)

**Comment by Fabricio20** [comment]
It's due to your `L!ignore list` channels (ignored channels).

Clear it up/remove channels to make them work again.

**Comment by firehunter02** [comment]
ok.Thanks
