### ISSUE TITLE
Command for removing music doesn't work

### ISSUE THREAD

**Issue by errorsans15** [Fabricio20/LewdWiki#77]
**_Hey, i have a problem with the bot, me and my friends were trying to remove some songs from the playlist but it doesn't work
We've tried with the song's full name but it just doesn't work, maybe can you please fix that or what should we do for that?_**

**Comment by Fabricio20** [comment]
Use the song id for now (Check `L!music list` to get a list of name -> id then remove with `L!remove id`).

**Comment by Fabricio20** [comment]
This has been fixed as far as I remember.
