### ISSUE TITLE
Clear and remove commands not working

### ISSUE THREAD

**Issue by xNightTitanx** [Fabricio20/LewdWiki#8]
I have admin status/am the server owner and i cannot clear the queue of songs nor remove certain songs, the list command brings up a 404 error page as well

**Comment by Fabricio20** [comment]
Gonna check these in a minute

**Comment by Fabricio20** [comment]
Music list is now fixed, as for song clean/remove, are you sure you have LewdBot Admin permissions or are the actual server owner?
