### ISSUE TITLE
Music, bug 

### ISSUE THREAD

**Issue by SonLory** [Fabricio20/LewdWiki#82]
Music don't work well

**Comment by Fabricio20** [comment]
I need more information, can you provide me with a description of what is happening?

Also send me the output for the `L!shard` command.

**Comment by SonLory** [comment]
Sorry, i don’t speak very good english. Anyway, the bot fails to play some music. It says  “Failed to load that song” and then stop to work. A while ago it was more smooth and it could play all the song..

**Comment by SonLory** [comment]
An other bug, when i type " @lewdbot join" and the name of the channel, it doesn't join
