### ISSUE TITLE
Pause Command

### ISSUE THREAD

**Issue by WootPH** [Fabricio20/LewdWiki#9]
[Lewd] doesn't have pause command? It's annoying when you stop the music and the bot will leave the channel so you have to "join" lewd everytime you stop the music. Please fix this as soon as possible, thanks Lewd [IMG]http://i68.tinypic.com/10gcwo5.jpg[/IMG]

**Comment by RobNO97** [comment]
Yes, and when you stop and sart it again it skip the song. A pause option would be cool

**Comment by Fabricio20** [comment]
The pause command was removed since people were not using it, and if it comes back, probably just for Patrons due to network usage (Since we will keep connected but doing nothing).
