### ISSUE TITLE
The bot is not working ! x-x 

### ISSUE THREAD

**Issue by TomAimeLesCanards** [Fabricio20/LewdWiki#90]
I write @Lewdbot play (link) and @Lewdbot leave but that's doesn't work ! Please help me. I can't make the bot leave or play music ..             Tom

**Comment by Fabricio20** [comment]
We are aware of the issue and working on a fix already, information about this will be posted on #news.

**Comment by Fabricio20** [comment]
It fixed itself somehow, closing this issue since everything looks functional.
