### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by JohnW101** [Fabricio20/LewdWiki#95]
Lewdbot NSFW Commands arent working.
╲⎝⧹𝓙𝓸𝓱𝓷⧸⎠╱: No images found on Danbooru, sorry.

**Comment by Fabricio20** [comment]
Hm, sounds like something broke again, gonna check later today.

**Comment by Fabricio20** [comment]
Looks functional here, not sure the cause, reopen/create a new issue if you see this happen again frequently.
