### ISSUE TITLE
Just Minor Errors

### ISSUE THREAD

**Issue by RocDog2357** [Fabricio20/LewdWiki#96]
Just a minor error with the Asuna01 in the shop. 
You spelt rapier incorrectly.
You spelt it as reaper.

**Comment by Fabricio20** [comment]
Riiight, thanks! Gonna fix later today :)

**Comment by Fabricio20** [comment]
So turns out I didn't fix this yet, whelp.

**Comment by Fabricio20** [comment]
It is now fixed (not yet in prod tho).
