### ISSUE TITLE
No items found with that name

### ISSUE THREAD

**Issue by popinloopy** [Fabricio20/LewdWiki#98]
I bought the FBI01 header and can't set it.
https://i.imgur.com/3lzmDuo.png
You can see that it's in my inventory, but the bot can't seem to find it.

**Comment by Fabricio20** [comment]
FBI01 is not a header, it's a card which is now a deprecated feature. I will be removing all cards from all accounts soon (and giving the cookies back).

**Comment by AGraber** [comment]
Please don't! But rather make it optional, I wouldn't like to lose my cards honestly!

**Comment by Fabricio20** [comment]
The card system is quite hard to maintain, as It requires graphics design work for each individual card. I can keep the card system, but they will need a new purpose, since they no longer contribute to badgemaking (This feature has already been removed due to it being buggy and hard to understand).
