### ISSUE TITLE
!giveme command claims it doesn't have permission to manage ranks

### ISSUE THREAD

**Issue by AGraber** [Fabricio20/LewdWiki#99]
`!giveme [role]` command claims that it doesn't have the necessary permissions to change roles, although I've set LewdBot as administrator on my server. Just in case, I also made sure that it also has the role permission.

This is actually an error related to the spanish langauge, as setting it to English fixes it:
~~While the help embed it's still working, it's descrption is `-- ERROR --` and all of its subcommands print the same `-- ERROR --`.~~

~~Despite that, `!giveme remove [role]` and `!giveme add [role]` still work regardless of returning `-- ERROR --`. But the main `!giveme [role]` is not working at all.~~

**Comment by AGraber** [comment]
The below seems to be an issue with the Spanish, the command now returns a more accurate text, although it's still incorrect.

**Comment by Fabricio20** [comment]
To properly be able to assign someone a role, the bot needs to meet all the following criteria:
- Have a role above the target member on the list of roles
- This role has to have manage roles permission
- This role has to be above the role being assigned to the target member
- The target member cannot be the guild owner (Owner status overrides all permissions)

**Comment by Fabricio20** [comment]
As for the translation issue, it's related to a recently implemented translation system that overrides the old one, so expect some strings to return `-- ERROR --` while their respective translations are not made in the new standard (see English.json).

**Comment by Fabricio20** [comment]
Should be fixed as of current prod build.
